//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace ProjektovanjeSoftvera.WebServis {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ekarta_ServisBinding", Namespace="http://ps")]
    public partial class Ekarta_ServisService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Ekarta_ServisOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKartaOperationCompleted;
        
        private System.Threading.SendOrPostCallback sacuvajKartuOperationCompleted;
        
        private System.Threading.SendOrPostCallback pronadjiKartuOperationCompleted;
        
        private System.Threading.SendOrPostCallback otkaziKartuOperationCompleted;
        
        private System.Threading.SendOrPostCallback popustiOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRedVoznjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback proveriVoznjuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ekarta_ServisService() {
            this.Url = global::ProjektovanjeSoftvera.Properties.Settings.Default.ProjektovanjeSoftvera_WebServis_Ekarta_ServisService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Ekarta_ServisCompletedEventHandler Ekarta_ServisCompleted;
        
        /// <remarks/>
        public event getKartaCompletedEventHandler getKartaCompleted;
        
        /// <remarks/>
        public event sacuvajKartuCompletedEventHandler sacuvajKartuCompleted;
        
        /// <remarks/>
        public event pronadjiKartuCompletedEventHandler pronadjiKartuCompleted;
        
        /// <remarks/>
        public event otkaziKartuCompletedEventHandler otkaziKartuCompleted;
        
        /// <remarks/>
        public event popustiCompletedEventHandler popustiCompleted;
        
        /// <remarks/>
        public event getRedVoznjeCompletedEventHandler getRedVoznjeCompleted;
        
        /// <remarks/>
        public event proveriVoznjuCompletedEventHandler proveriVoznjuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#Ekarta_Servis", RequestNamespace="http://ps", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Ekarta_Servis() {
            this.Invoke("Ekarta_Servis", new object[0]);
        }
        
        /// <remarks/>
        public void Ekarta_ServisAsync() {
            this.Ekarta_ServisAsync(null);
        }
        
        /// <remarks/>
        public void Ekarta_ServisAsync(object userState) {
            if ((this.Ekarta_ServisOperationCompleted == null)) {
                this.Ekarta_ServisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEkarta_ServisOperationCompleted);
            }
            this.InvokeAsync("Ekarta_Servis", new object[0], this.Ekarta_ServisOperationCompleted, userState);
        }
        
        private void OnEkarta_ServisOperationCompleted(object arg) {
            if ((this.Ekarta_ServisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ekarta_ServisCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#getKarta", RequestNamespace="http://ps", ResponseNamespace="http://ps", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Karta getKarta() {
            object[] results = this.Invoke("getKarta", new object[0]);
            return ((Application_Model_Karta)(results[0]));
        }
        
        /// <remarks/>
        public void getKartaAsync() {
            this.getKartaAsync(null);
        }
        
        /// <remarks/>
        public void getKartaAsync(object userState) {
            if ((this.getKartaOperationCompleted == null)) {
                this.getKartaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKartaOperationCompleted);
            }
            this.InvokeAsync("getKarta", new object[0], this.getKartaOperationCompleted, userState);
        }
        
        private void OngetKartaOperationCompleted(object arg) {
            if ((this.getKartaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKartaCompleted(this, new getKartaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#sacuvajKartu", RequestNamespace="http://ps", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sacuvajKartu([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Application_Model_Karta @object) {
            this.Invoke("sacuvajKartu", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void sacuvajKartuAsync(Application_Model_Karta @object) {
            this.sacuvajKartuAsync(@object, null);
        }
        
        /// <remarks/>
        public void sacuvajKartuAsync(Application_Model_Karta @object, object userState) {
            if ((this.sacuvajKartuOperationCompleted == null)) {
                this.sacuvajKartuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsacuvajKartuOperationCompleted);
            }
            this.InvokeAsync("sacuvajKartu", new object[] {
                        @object}, this.sacuvajKartuOperationCompleted, userState);
        }
        
        private void OnsacuvajKartuOperationCompleted(object arg) {
            if ((this.sacuvajKartuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sacuvajKartuCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#pronadjiKartu", RequestNamespace="http://ps", ResponseNamespace="http://ps", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Karta pronadjiKartu([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id) {
            object[] results = this.Invoke("pronadjiKartu", new object[] {
                        id});
            return ((Application_Model_Karta)(results[0]));
        }
        
        /// <remarks/>
        public void pronadjiKartuAsync(int id) {
            this.pronadjiKartuAsync(id, null);
        }
        
        /// <remarks/>
        public void pronadjiKartuAsync(int id, object userState) {
            if ((this.pronadjiKartuOperationCompleted == null)) {
                this.pronadjiKartuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpronadjiKartuOperationCompleted);
            }
            this.InvokeAsync("pronadjiKartu", new object[] {
                        id}, this.pronadjiKartuOperationCompleted, userState);
        }
        
        private void OnpronadjiKartuOperationCompleted(object arg) {
            if ((this.pronadjiKartuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pronadjiKartuCompleted(this, new pronadjiKartuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#otkaziKartu", RequestNamespace="http://ps", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void otkaziKartu([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id) {
            this.Invoke("otkaziKartu", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void otkaziKartuAsync(int id) {
            this.otkaziKartuAsync(id, null);
        }
        
        /// <remarks/>
        public void otkaziKartuAsync(int id, object userState) {
            if ((this.otkaziKartuOperationCompleted == null)) {
                this.otkaziKartuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnotkaziKartuOperationCompleted);
            }
            this.InvokeAsync("otkaziKartu", new object[] {
                        id}, this.otkaziKartuOperationCompleted, userState);
        }
        
        private void OnotkaziKartuOperationCompleted(object arg) {
            if ((this.otkaziKartuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.otkaziKartuCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#popusti", RequestNamespace="http://ps", ResponseNamespace="http://ps", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string popusti() {
            object[] results = this.Invoke("popusti", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void popustiAsync() {
            this.popustiAsync(null);
        }
        
        /// <remarks/>
        public void popustiAsync(object userState) {
            if ((this.popustiOperationCompleted == null)) {
                this.popustiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpopustiOperationCompleted);
            }
            this.InvokeAsync("popusti", new object[0], this.popustiOperationCompleted, userState);
        }
        
        private void OnpopustiOperationCompleted(object arg) {
            if ((this.popustiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.popustiCompleted(this, new popustiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#getRedVoznje", RequestNamespace="http://ps", ResponseNamespace="http://ps", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Redvoznje getRedVoznje() {
            object[] results = this.Invoke("getRedVoznje", new object[0]);
            return ((Application_Model_Redvoznje)(results[0]));
        }
        
        /// <remarks/>
        public void getRedVoznjeAsync() {
            this.getRedVoznjeAsync(null);
        }
        
        /// <remarks/>
        public void getRedVoznjeAsync(object userState) {
            if ((this.getRedVoznjeOperationCompleted == null)) {
                this.getRedVoznjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRedVoznjeOperationCompleted);
            }
            this.InvokeAsync("getRedVoznje", new object[0], this.getRedVoznjeOperationCompleted, userState);
        }
        
        private void OngetRedVoznjeOperationCompleted(object arg) {
            if ((this.getRedVoznjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRedVoznjeCompleted(this, new getRedVoznjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps#proveriVoznju", RequestNamespace="http://ps", ResponseNamespace="http://ps", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool proveriVoznju([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @string) {
            object[] results = this.Invoke("proveriVoznju", new object[] {
                        @string});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void proveriVoznjuAsync(string @string) {
            this.proveriVoznjuAsync(@string, null);
        }
        
        /// <remarks/>
        public void proveriVoznjuAsync(string @string, object userState) {
            if ((this.proveriVoznjuOperationCompleted == null)) {
                this.proveriVoznjuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnproveriVoznjuOperationCompleted);
            }
            this.InvokeAsync("proveriVoznju", new object[] {
                        @string}, this.proveriVoznjuOperationCompleted, userState);
        }
        
        private void OnproveriVoznjuOperationCompleted(object arg) {
            if ((this.proveriVoznjuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.proveriVoznjuCompleted(this, new proveriVoznjuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps")]
    public partial class Application_Model_Karta {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps")]
    public partial class Application_Model_Redvoznje {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Ekarta_ServisCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getKartaCompletedEventHandler(object sender, getKartaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKartaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKartaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Karta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Karta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void sacuvajKartuCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void pronadjiKartuCompletedEventHandler(object sender, pronadjiKartuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pronadjiKartuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pronadjiKartuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Karta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Karta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void otkaziKartuCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void popustiCompletedEventHandler(object sender, popustiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class popustiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal popustiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getRedVoznjeCompletedEventHandler(object sender, getRedVoznjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRedVoznjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRedVoznjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Redvoznje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Redvoznje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void proveriVoznjuCompletedEventHandler(object sender, proveriVoznjuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class proveriVoznjuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal proveriVoznjuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591