//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektovanjeSoftvera.AdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ps/Admin", ConfigurationName="AdminService.Ekarta_AdminPort")]
    public interface Ekarta_AdminPort {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#Ekarta_Admin")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void Ekarta_Admin();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setPopust")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setPopust(string @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetPopust")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetPopust(ProjektovanjeSoftvera.AdminService.Application_Model_Popust @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setKarta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetKarta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#deactivate")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void deactivate(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setStanica")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setStanica(string @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getStanice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Application_Model_Stanica[] getStanice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getStanicu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProjektovanjeSoftvera.AdminService.Application_Model_Stanica getStanicu(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetStanica")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Stanica @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setTrasa")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setTrasa(string @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getTrase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Application_Model_Trasa[] getTrase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getTrasu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProjektovanjeSoftvera.AdminService.Application_Model_Trasa getTrasu(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetTrasa")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetTrasa(ProjektovanjeSoftvera.AdminService.Application_Model_Trasa @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setRedVoznje")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setRedVoznje(string @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getRedVoznje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Application_Model_Redvoznje[] getRedVoznje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getJedanRedVoznje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje getJedanRedVoznje(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#proveraDaLiPostoji", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool proveraDaLiPostoji(int idTrasa, int dan, string vreme);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetRedVoznje")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetRedVoznje(ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje @object);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setOtkazanaVoznja")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void setOtkazanaVoznja(string @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getOtkazaneVoznje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Application_Model_Otkazanavoznja[] getOtkazaneVoznje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getOtkazanaVoznja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja getOtkazanaVoznja();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetOtkazanaVoznja")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja @object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getTrasaStanice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Application_Model_Trasastanica[] getTrasaStanice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getTrasaStanica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica getTrasaStanica(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetTrasaStanica")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void unsetTrasaStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica @object);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Popust : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Trasastanica : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Otkazanavoznja : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Redvoznje : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Trasa : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Stanica : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Karta : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ekarta_AdminPortChannel : ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ekarta_AdminPortClient : System.ServiceModel.ClientBase<ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort>, ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort {
        
        public Ekarta_AdminPortClient() {
        }
        
        public Ekarta_AdminPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ekarta_AdminPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ekarta_AdminPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ekarta_AdminPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ekarta_Admin() {
            base.Channel.Ekarta_Admin();
        }
        
        public void setPopust(string @object) {
            base.Channel.setPopust(@object);
        }
        
        public void unsetPopust(ProjektovanjeSoftvera.AdminService.Application_Model_Popust @object) {
            base.Channel.unsetPopust(@object);
        }
        
        public void setKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object) {
            base.Channel.setKarta(@object);
        }
        
        public void unsetKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object) {
            base.Channel.unsetKarta(@object);
        }
        
        public void deactivate(int id) {
            base.Channel.deactivate(id);
        }
        
        public void setStanica(string @object) {
            base.Channel.setStanica(@object);
        }
        
        public Application_Model_Stanica[] getStanice() {
            return base.Channel.getStanice();
        }
        
        public ProjektovanjeSoftvera.AdminService.Application_Model_Stanica getStanicu(int id) {
            return base.Channel.getStanicu(id);
        }
        
        public void unsetStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Stanica @object) {
            base.Channel.unsetStanica(@object);
        }
        
        public void setTrasa(string @object) {
            base.Channel.setTrasa(@object);
        }
        
        public Application_Model_Trasa[] getTrase() {
            return base.Channel.getTrase();
        }
        
        public ProjektovanjeSoftvera.AdminService.Application_Model_Trasa getTrasu(int id) {
            return base.Channel.getTrasu(id);
        }
        
        public void unsetTrasa(ProjektovanjeSoftvera.AdminService.Application_Model_Trasa @object) {
            base.Channel.unsetTrasa(@object);
        }
        
        public void setRedVoznje(string @object) {
            base.Channel.setRedVoznje(@object);
        }
        
        public Application_Model_Redvoznje[] getRedVoznje() {
            return base.Channel.getRedVoznje();
        }
        
        public ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje getJedanRedVoznje(int id) {
            return base.Channel.getJedanRedVoznje(id);
        }
        
        public bool proveraDaLiPostoji(int idTrasa, int dan, string vreme) {
            return base.Channel.proveraDaLiPostoji(idTrasa, dan, vreme);
        }
        
        public void unsetRedVoznje(ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje @object) {
            base.Channel.unsetRedVoznje(@object);
        }
        
        public void setOtkazanaVoznja(string @object) {
            base.Channel.setOtkazanaVoznja(@object);
        }
        
        public Application_Model_Otkazanavoznja[] getOtkazaneVoznje() {
            return base.Channel.getOtkazaneVoznje();
        }
        
        public ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja getOtkazanaVoznja() {
            return base.Channel.getOtkazanaVoznja();
        }
        
        public void unsetOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja @object) {
            base.Channel.unsetOtkazanaVoznja(@object);
        }
        
        public Application_Model_Trasastanica[] getTrasaStanice() {
            return base.Channel.getTrasaStanice();
        }
        
        public ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica getTrasaStanica(int id) {
            return base.Channel.getTrasaStanica(id);
        }
        
        public void unsetTrasaStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica @object) {
            base.Channel.unsetTrasaStanica(@object);
        }
    }
}
