//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektovanjeSoftvera.AdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ps/Admin", ConfigurationName="AdminService.Ekarta_AdminPort")]
    public interface Ekarta_AdminPort {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#Ekarta_Admin")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ekarta_Admin();
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setPopust")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setPopust(ProjektovanjeSoftvera.AdminService.setPopust request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetPopust")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetPopust(ProjektovanjeSoftvera.AdminService.unsetPopust request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setKarta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setKarta(ProjektovanjeSoftvera.AdminService.setKarta request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetKarta")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetKarta(ProjektovanjeSoftvera.AdminService.unsetKarta request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#deactivate")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deactivate(ProjektovanjeSoftvera.AdminService.deactivate request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setStanica")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setStanica(ProjektovanjeSoftvera.AdminService.setStanica request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetStanica")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetStanica(ProjektovanjeSoftvera.AdminService.unsetStanica request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setTrasa")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setTrasa(ProjektovanjeSoftvera.AdminService.setTrasa request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetTrasa")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetTrasa(ProjektovanjeSoftvera.AdminService.unsetTrasa request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setRedVoznje")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setRedVoznje(ProjektovanjeSoftvera.AdminService.setRedVoznje request);
        
        // CODEGEN: Parameter 'getJedanRedVoznjeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#getJedanRedVoznje", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeResponse getJedanRedVoznje(ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeRequest request);
        
        // CODEGEN: Parameter 'proveraDaLiPostojiResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ps/Admin#proveraDaLiPostoji", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiResponse proveraDaLiPostoji(ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiRequest request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetRedVoznje")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetRedVoznje(ProjektovanjeSoftvera.AdminService.unsetRedVoznje request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#setOtkazanaVoznja")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.setOtkazanaVoznja request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetOtkazanaVoznja")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.unsetOtkazanaVoznja request);
        
        // CODEGEN: Parameter 'object' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps/Admin#unsetTrasaStanica")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void unsetTrasaStanica(ProjektovanjeSoftvera.AdminService.unsetTrasaStanica request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPopust", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class setPopust {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @object;
        
        public setPopust() {
        }
        
        public setPopust(string @object) {
            this.@object = @object;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Popust : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Trasastanica : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Otkazanavoznja : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Redvoznje : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Trasa : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Stanica : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Karta : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetPopust", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetPopust {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Popust @object;
        
        public unsetPopust() {
        }
        
        public unsetPopust(ProjektovanjeSoftvera.AdminService.Application_Model_Popust @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setKarta", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class setKarta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object;
        
        public setKarta() {
        }
        
        public setKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetKarta", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetKarta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object;
        
        public unsetKarta() {
        }
        
        public unsetKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deactivate", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class deactivate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public deactivate() {
        }
        
        public deactivate(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setStanica", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class setStanica {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @object;
        
        public setStanica() {
        }
        
        public setStanica(string @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetStanica", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetStanica {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Stanica @object;
        
        public unsetStanica() {
        }
        
        public unsetStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Stanica @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setTrasa", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class setTrasa {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @object;
        
        public setTrasa() {
        }
        
        public setTrasa(string @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetTrasa", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetTrasa {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Trasa @object;
        
        public unsetTrasa() {
        }
        
        public unsetTrasa(ProjektovanjeSoftvera.AdminService.Application_Model_Trasa @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setRedVoznje", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class setRedVoznje {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @object;
        
        public setRedVoznje() {
        }
        
        public setRedVoznje(string @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJedanRedVoznje", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class getJedanRedVoznjeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public getJedanRedVoznjeRequest() {
        }
        
        public getJedanRedVoznjeRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJedanRedVoznjeResponse", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class getJedanRedVoznjeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje getJedanRedVoznjeResult;
        
        public getJedanRedVoznjeResponse() {
        }
        
        public getJedanRedVoznjeResponse(ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje getJedanRedVoznjeResult) {
            this.getJedanRedVoznjeResult = getJedanRedVoznjeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="proveraDaLiPostoji", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class proveraDaLiPostojiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTrasa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vreme;
        
        public proveraDaLiPostojiRequest() {
        }
        
        public proveraDaLiPostojiRequest(int idTrasa, int dan, string vreme) {
            this.idTrasa = idTrasa;
            this.dan = dan;
            this.vreme = vreme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="proveraDaLiPostojiResponse", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class proveraDaLiPostojiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool proveraDaLiPostojiResult;
        
        public proveraDaLiPostojiResponse() {
        }
        
        public proveraDaLiPostojiResponse(bool proveraDaLiPostojiResult) {
            this.proveraDaLiPostojiResult = proveraDaLiPostojiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetRedVoznje", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetRedVoznje {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje @object;
        
        public unsetRedVoznje() {
        }
        
        public unsetRedVoznje(ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setOtkazanaVoznja", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class setOtkazanaVoznja {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @object;
        
        public setOtkazanaVoznja() {
        }
        
        public setOtkazanaVoznja(string @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetOtkazanaVoznja", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetOtkazanaVoznja {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja @object;
        
        public unsetOtkazanaVoznja() {
        }
        
        public unsetOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja @object) {
            this.@object = @object;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="unsetTrasaStanica", WrapperNamespace="http://ps/Admin", IsWrapped=true)]
    public partial class unsetTrasaStanica {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ps/Admin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica @object;
        
        public unsetTrasaStanica() {
        }
        
        public unsetTrasaStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica @object) {
            this.@object = @object;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ekarta_AdminPortChannel : ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ekarta_AdminPortClient : System.ServiceModel.ClientBase<ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort>, ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort {
        
        public Ekarta_AdminPortClient() {
        }
        
        public Ekarta_AdminPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ekarta_AdminPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ekarta_AdminPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ekarta_AdminPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ekarta_Admin() {
            base.Channel.Ekarta_Admin();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.setPopust(ProjektovanjeSoftvera.AdminService.setPopust request) {
            base.Channel.setPopust(request);
        }
        
        public void setPopust(string @object) {
            ProjektovanjeSoftvera.AdminService.setPopust inValue = new ProjektovanjeSoftvera.AdminService.setPopust();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).setPopust(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetPopust(ProjektovanjeSoftvera.AdminService.unsetPopust request) {
            base.Channel.unsetPopust(request);
        }
        
        public void unsetPopust(ProjektovanjeSoftvera.AdminService.Application_Model_Popust @object) {
            ProjektovanjeSoftvera.AdminService.unsetPopust inValue = new ProjektovanjeSoftvera.AdminService.unsetPopust();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetPopust(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.setKarta(ProjektovanjeSoftvera.AdminService.setKarta request) {
            base.Channel.setKarta(request);
        }
        
        public void setKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object) {
            ProjektovanjeSoftvera.AdminService.setKarta inValue = new ProjektovanjeSoftvera.AdminService.setKarta();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).setKarta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetKarta(ProjektovanjeSoftvera.AdminService.unsetKarta request) {
            base.Channel.unsetKarta(request);
        }
        
        public void unsetKarta(ProjektovanjeSoftvera.AdminService.Application_Model_Karta @object) {
            ProjektovanjeSoftvera.AdminService.unsetKarta inValue = new ProjektovanjeSoftvera.AdminService.unsetKarta();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetKarta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.deactivate(ProjektovanjeSoftvera.AdminService.deactivate request) {
            base.Channel.deactivate(request);
        }
        
        public void deactivate(int id) {
            ProjektovanjeSoftvera.AdminService.deactivate inValue = new ProjektovanjeSoftvera.AdminService.deactivate();
            inValue.id = id;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).deactivate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.setStanica(ProjektovanjeSoftvera.AdminService.setStanica request) {
            base.Channel.setStanica(request);
        }
        
        public void setStanica(string @object) {
            ProjektovanjeSoftvera.AdminService.setStanica inValue = new ProjektovanjeSoftvera.AdminService.setStanica();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).setStanica(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetStanica(ProjektovanjeSoftvera.AdminService.unsetStanica request) {
            base.Channel.unsetStanica(request);
        }
        
        public void unsetStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Stanica @object) {
            ProjektovanjeSoftvera.AdminService.unsetStanica inValue = new ProjektovanjeSoftvera.AdminService.unsetStanica();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetStanica(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.setTrasa(ProjektovanjeSoftvera.AdminService.setTrasa request) {
            base.Channel.setTrasa(request);
        }
        
        public void setTrasa(string @object) {
            ProjektovanjeSoftvera.AdminService.setTrasa inValue = new ProjektovanjeSoftvera.AdminService.setTrasa();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).setTrasa(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetTrasa(ProjektovanjeSoftvera.AdminService.unsetTrasa request) {
            base.Channel.unsetTrasa(request);
        }
        
        public void unsetTrasa(ProjektovanjeSoftvera.AdminService.Application_Model_Trasa @object) {
            ProjektovanjeSoftvera.AdminService.unsetTrasa inValue = new ProjektovanjeSoftvera.AdminService.unsetTrasa();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetTrasa(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.setRedVoznje(ProjektovanjeSoftvera.AdminService.setRedVoznje request) {
            base.Channel.setRedVoznje(request);
        }
        
        public void setRedVoznje(string @object) {
            ProjektovanjeSoftvera.AdminService.setRedVoznje inValue = new ProjektovanjeSoftvera.AdminService.setRedVoznje();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).setRedVoznje(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeResponse ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.getJedanRedVoznje(ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeRequest request) {
            return base.Channel.getJedanRedVoznje(request);
        }
        
        public ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje getJedanRedVoznje(int id) {
            ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeRequest inValue = new ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeRequest();
            inValue.id = id;
            ProjektovanjeSoftvera.AdminService.getJedanRedVoznjeResponse retVal = ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).getJedanRedVoznje(inValue);
            return retVal.getJedanRedVoznjeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiResponse ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.proveraDaLiPostoji(ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiRequest request) {
            return base.Channel.proveraDaLiPostoji(request);
        }
        
        public bool proveraDaLiPostoji(int idTrasa, int dan, string vreme) {
            ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiRequest inValue = new ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiRequest();
            inValue.idTrasa = idTrasa;
            inValue.dan = dan;
            inValue.vreme = vreme;
            ProjektovanjeSoftvera.AdminService.proveraDaLiPostojiResponse retVal = ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).proveraDaLiPostoji(inValue);
            return retVal.proveraDaLiPostojiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetRedVoznje(ProjektovanjeSoftvera.AdminService.unsetRedVoznje request) {
            base.Channel.unsetRedVoznje(request);
        }
        
        public void unsetRedVoznje(ProjektovanjeSoftvera.AdminService.Application_Model_Redvoznje @object) {
            ProjektovanjeSoftvera.AdminService.unsetRedVoznje inValue = new ProjektovanjeSoftvera.AdminService.unsetRedVoznje();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetRedVoznje(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.setOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.setOtkazanaVoznja request) {
            base.Channel.setOtkazanaVoznja(request);
        }
        
        public void setOtkazanaVoznja(string @object) {
            ProjektovanjeSoftvera.AdminService.setOtkazanaVoznja inValue = new ProjektovanjeSoftvera.AdminService.setOtkazanaVoznja();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).setOtkazanaVoznja(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.unsetOtkazanaVoznja request) {
            base.Channel.unsetOtkazanaVoznja(request);
        }
        
        public void unsetOtkazanaVoznja(ProjektovanjeSoftvera.AdminService.Application_Model_Otkazanavoznja @object) {
            ProjektovanjeSoftvera.AdminService.unsetOtkazanaVoznja inValue = new ProjektovanjeSoftvera.AdminService.unsetOtkazanaVoznja();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetOtkazanaVoznja(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort.unsetTrasaStanica(ProjektovanjeSoftvera.AdminService.unsetTrasaStanica request) {
            base.Channel.unsetTrasaStanica(request);
        }
        
        public void unsetTrasaStanica(ProjektovanjeSoftvera.AdminService.Application_Model_Trasastanica @object) {
            ProjektovanjeSoftvera.AdminService.unsetTrasaStanica inValue = new ProjektovanjeSoftvera.AdminService.unsetTrasaStanica();
            inValue.@object = @object;
            ((ProjektovanjeSoftvera.AdminService.Ekarta_AdminPort)(this)).unsetTrasaStanica(inValue);
        }
    }
}
