//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace ProjektovanjeSoftvera.AdminWebServis {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Ekarta_AdminBinding", Namespace="http://ps/Admin")]
    public partial class Ekarta_AdminService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Ekarta_AdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPopustOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPopustOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetPopustOperationCompleted;
        
        private System.Threading.SendOrPostCallback setKartaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKartaOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetKartaOperationCompleted;
        
        private System.Threading.SendOrPostCallback deactivateOperationCompleted;
        
        private System.Threading.SendOrPostCallback setStanicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStanicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetStanicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTrasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTrasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetTrasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRedVoznjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRedVoznjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetRedVoznjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback setOtkazanaVoznjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOtkazanaVoznjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetOtkazanaVoznjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTrasaStanicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTrasaStanicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsetTrasaStanicaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Ekarta_AdminService() {
            this.Url = global::ProjektovanjeSoftvera.Properties.Settings.Default.ProjektovanjeSoftvera_AdminWebServis_Ekarta_AdminService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Ekarta_AdminCompletedEventHandler Ekarta_AdminCompleted;
        
        /// <remarks/>
        public event setPopustCompletedEventHandler setPopustCompleted;
        
        /// <remarks/>
        public event getPopustCompletedEventHandler getPopustCompleted;
        
        /// <remarks/>
        public event unsetPopustCompletedEventHandler unsetPopustCompleted;
        
        /// <remarks/>
        public event setKartaCompletedEventHandler setKartaCompleted;
        
        /// <remarks/>
        public event getKartaCompletedEventHandler getKartaCompleted;
        
        /// <remarks/>
        public event unsetKartaCompletedEventHandler unsetKartaCompleted;
        
        /// <remarks/>
        public event deactivateCompletedEventHandler deactivateCompleted;
        
        /// <remarks/>
        public event setStanicaCompletedEventHandler setStanicaCompleted;
        
        /// <remarks/>
        public event getStanicaCompletedEventHandler getStanicaCompleted;
        
        /// <remarks/>
        public event unsetStanicaCompletedEventHandler unsetStanicaCompleted;
        
        /// <remarks/>
        public event setTrasaCompletedEventHandler setTrasaCompleted;
        
        /// <remarks/>
        public event getTrasaCompletedEventHandler getTrasaCompleted;
        
        /// <remarks/>
        public event unsetTrasaCompletedEventHandler unsetTrasaCompleted;
        
        /// <remarks/>
        public event setRedVoznjeCompletedEventHandler setRedVoznjeCompleted;
        
        /// <remarks/>
        public event getRedVoznjeCompletedEventHandler getRedVoznjeCompleted;
        
        /// <remarks/>
        public event unsetRedVoznjeCompletedEventHandler unsetRedVoznjeCompleted;
        
        /// <remarks/>
        public event setOtkazanaVoznjaCompletedEventHandler setOtkazanaVoznjaCompleted;
        
        /// <remarks/>
        public event getOtkazanaVoznjaCompletedEventHandler getOtkazanaVoznjaCompleted;
        
        /// <remarks/>
        public event unsetOtkazanaVoznjaCompletedEventHandler unsetOtkazanaVoznjaCompleted;
        
        /// <remarks/>
        public event setTrasaStanicaCompletedEventHandler setTrasaStanicaCompleted;
        
        /// <remarks/>
        public event getTrasaStanicaCompletedEventHandler getTrasaStanicaCompleted;
        
        /// <remarks/>
        public event unsetTrasaStanicaCompletedEventHandler unsetTrasaStanicaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#Ekarta_Admin", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Ekarta_Admin() {
            this.Invoke("Ekarta_Admin", new object[0]);
        }
        
        /// <remarks/>
        public void Ekarta_AdminAsync() {
            this.Ekarta_AdminAsync(null);
        }
        
        /// <remarks/>
        public void Ekarta_AdminAsync(object userState) {
            if ((this.Ekarta_AdminOperationCompleted == null)) {
                this.Ekarta_AdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEkarta_AdminOperationCompleted);
            }
            this.InvokeAsync("Ekarta_Admin", new object[0], this.Ekarta_AdminOperationCompleted, userState);
        }
        
        private void OnEkarta_AdminOperationCompleted(object arg) {
            if ((this.Ekarta_AdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ekarta_AdminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setPopust", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setPopust([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("setPopust", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setPopustAsync(string @object) {
            this.setPopustAsync(@object, null);
        }
        
        /// <remarks/>
        public void setPopustAsync(string @object, object userState) {
            if ((this.setPopustOperationCompleted == null)) {
                this.setPopustOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPopustOperationCompleted);
            }
            this.InvokeAsync("setPopust", new object[] {
                        @object}, this.setPopustOperationCompleted, userState);
        }
        
        private void OnsetPopustOperationCompleted(object arg) {
            if ((this.setPopustCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPopustCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getPopust", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Popust getPopust([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("getPopust", new object[] {
                        id});
            return ((Application_Model_Popust)(results[0]));
        }
        
        /// <remarks/>
        public void getPopustAsync(System.Nullable<int> id) {
            this.getPopustAsync(id, null);
        }
        
        /// <remarks/>
        public void getPopustAsync(System.Nullable<int> id, object userState) {
            if ((this.getPopustOperationCompleted == null)) {
                this.getPopustOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPopustOperationCompleted);
            }
            this.InvokeAsync("getPopust", new object[] {
                        id}, this.getPopustOperationCompleted, userState);
        }
        
        private void OngetPopustOperationCompleted(object arg) {
            if ((this.getPopustCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPopustCompleted(this, new getPopustCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetPopust", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetPopust([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetPopust", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetPopustAsync(string @object) {
            this.unsetPopustAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetPopustAsync(string @object, object userState) {
            if ((this.unsetPopustOperationCompleted == null)) {
                this.unsetPopustOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetPopustOperationCompleted);
            }
            this.InvokeAsync("unsetPopust", new object[] {
                        @object}, this.unsetPopustOperationCompleted, userState);
        }
        
        private void OnunsetPopustOperationCompleted(object arg) {
            if ((this.unsetPopustCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetPopustCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setKarta", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setKarta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("setKarta", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setKartaAsync(string @object) {
            this.setKartaAsync(@object, null);
        }
        
        /// <remarks/>
        public void setKartaAsync(string @object, object userState) {
            if ((this.setKartaOperationCompleted == null)) {
                this.setKartaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetKartaOperationCompleted);
            }
            this.InvokeAsync("setKarta", new object[] {
                        @object}, this.setKartaOperationCompleted, userState);
        }
        
        private void OnsetKartaOperationCompleted(object arg) {
            if ((this.setKartaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setKartaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getKarta", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Karta getKarta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("getKarta", new object[] {
                        id});
            return ((Application_Model_Karta)(results[0]));
        }
        
        /// <remarks/>
        public void getKartaAsync(System.Nullable<int> id) {
            this.getKartaAsync(id, null);
        }
        
        /// <remarks/>
        public void getKartaAsync(System.Nullable<int> id, object userState) {
            if ((this.getKartaOperationCompleted == null)) {
                this.getKartaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKartaOperationCompleted);
            }
            this.InvokeAsync("getKarta", new object[] {
                        id}, this.getKartaOperationCompleted, userState);
        }
        
        private void OngetKartaOperationCompleted(object arg) {
            if ((this.getKartaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKartaCompleted(this, new getKartaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetKarta", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetKarta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetKarta", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetKartaAsync(string @object) {
            this.unsetKartaAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetKartaAsync(string @object, object userState) {
            if ((this.unsetKartaOperationCompleted == null)) {
                this.unsetKartaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetKartaOperationCompleted);
            }
            this.InvokeAsync("unsetKarta", new object[] {
                        @object}, this.unsetKartaOperationCompleted, userState);
        }
        
        private void OnunsetKartaOperationCompleted(object arg) {
            if ((this.unsetKartaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetKartaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#deactivate", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deactivate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id) {
            this.Invoke("deactivate", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void deactivateAsync(int id) {
            this.deactivateAsync(id, null);
        }
        
        /// <remarks/>
        public void deactivateAsync(int id, object userState) {
            if ((this.deactivateOperationCompleted == null)) {
                this.deactivateOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeactivateOperationCompleted);
            }
            this.InvokeAsync("deactivate", new object[] {
                        id}, this.deactivateOperationCompleted, userState);
        }
        
        private void OndeactivateOperationCompleted(object arg) {
            if ((this.deactivateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deactivateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setStanica", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setStanica([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("setStanica", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setStanicaAsync(string @object) {
            this.setStanicaAsync(@object, null);
        }
        
        /// <remarks/>
        public void setStanicaAsync(string @object, object userState) {
            if ((this.setStanicaOperationCompleted == null)) {
                this.setStanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetStanicaOperationCompleted);
            }
            this.InvokeAsync("setStanica", new object[] {
                        @object}, this.setStanicaOperationCompleted, userState);
        }
        
        private void OnsetStanicaOperationCompleted(object arg) {
            if ((this.setStanicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setStanicaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getStanica", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Stanica getStanica([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id) {
            object[] results = this.Invoke("getStanica", new object[] {
                        id});
            return ((Application_Model_Stanica)(results[0]));
        }
        
        /// <remarks/>
        public void getStanicaAsync(int id) {
            this.getStanicaAsync(id, null);
        }
        
        /// <remarks/>
        public void getStanicaAsync(int id, object userState) {
            if ((this.getStanicaOperationCompleted == null)) {
                this.getStanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStanicaOperationCompleted);
            }
            this.InvokeAsync("getStanica", new object[] {
                        id}, this.getStanicaOperationCompleted, userState);
        }
        
        private void OngetStanicaOperationCompleted(object arg) {
            if ((this.getStanicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStanicaCompleted(this, new getStanicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetStanica", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetStanica([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetStanica", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetStanicaAsync(string @object) {
            this.unsetStanicaAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetStanicaAsync(string @object, object userState) {
            if ((this.unsetStanicaOperationCompleted == null)) {
                this.unsetStanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetStanicaOperationCompleted);
            }
            this.InvokeAsync("unsetStanica", new object[] {
                        @object}, this.unsetStanicaOperationCompleted, userState);
        }
        
        private void OnunsetStanicaOperationCompleted(object arg) {
            if ((this.unsetStanicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetStanicaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setTrasa", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setTrasa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Application_Model_Trasa @object) {
            this.Invoke("setTrasa", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setTrasaAsync(Application_Model_Trasa @object) {
            this.setTrasaAsync(@object, null);
        }
        
        /// <remarks/>
        public void setTrasaAsync(Application_Model_Trasa @object, object userState) {
            if ((this.setTrasaOperationCompleted == null)) {
                this.setTrasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTrasaOperationCompleted);
            }
            this.InvokeAsync("setTrasa", new object[] {
                        @object}, this.setTrasaOperationCompleted, userState);
        }
        
        private void OnsetTrasaOperationCompleted(object arg) {
            if ((this.setTrasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTrasaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getTrasa", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Trasa getTrasa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("getTrasa", new object[] {
                        id});
            return ((Application_Model_Trasa)(results[0]));
        }
        
        /// <remarks/>
        public void getTrasaAsync(System.Nullable<int> id) {
            this.getTrasaAsync(id, null);
        }
        
        /// <remarks/>
        public void getTrasaAsync(System.Nullable<int> id, object userState) {
            if ((this.getTrasaOperationCompleted == null)) {
                this.getTrasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTrasaOperationCompleted);
            }
            this.InvokeAsync("getTrasa", new object[] {
                        id}, this.getTrasaOperationCompleted, userState);
        }
        
        private void OngetTrasaOperationCompleted(object arg) {
            if ((this.getTrasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTrasaCompleted(this, new getTrasaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetTrasa", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetTrasa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetTrasa", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetTrasaAsync(string @object) {
            this.unsetTrasaAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetTrasaAsync(string @object, object userState) {
            if ((this.unsetTrasaOperationCompleted == null)) {
                this.unsetTrasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetTrasaOperationCompleted);
            }
            this.InvokeAsync("unsetTrasa", new object[] {
                        @object}, this.unsetTrasaOperationCompleted, userState);
        }
        
        private void OnunsetTrasaOperationCompleted(object arg) {
            if ((this.unsetTrasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetTrasaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setRedVoznje", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setRedVoznje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("setRedVoznje", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setRedVoznjeAsync(string @object) {
            this.setRedVoznjeAsync(@object, null);
        }
        
        /// <remarks/>
        public void setRedVoznjeAsync(string @object, object userState) {
            if ((this.setRedVoznjeOperationCompleted == null)) {
                this.setRedVoznjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRedVoznjeOperationCompleted);
            }
            this.InvokeAsync("setRedVoznje", new object[] {
                        @object}, this.setRedVoznjeOperationCompleted, userState);
        }
        
        private void OnsetRedVoznjeOperationCompleted(object arg) {
            if ((this.setRedVoznjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRedVoznjeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getRedVoznje", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Redvoznje getRedVoznje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("getRedVoznje", new object[] {
                        id});
            return ((Application_Model_Redvoznje)(results[0]));
        }
        
        /// <remarks/>
        public void getRedVoznjeAsync(System.Nullable<int> id) {
            this.getRedVoznjeAsync(id, null);
        }
        
        /// <remarks/>
        public void getRedVoznjeAsync(System.Nullable<int> id, object userState) {
            if ((this.getRedVoznjeOperationCompleted == null)) {
                this.getRedVoznjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRedVoznjeOperationCompleted);
            }
            this.InvokeAsync("getRedVoznje", new object[] {
                        id}, this.getRedVoznjeOperationCompleted, userState);
        }
        
        private void OngetRedVoznjeOperationCompleted(object arg) {
            if ((this.getRedVoznjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRedVoznjeCompleted(this, new getRedVoznjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetRedVoznje", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetRedVoznje([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetRedVoznje", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetRedVoznjeAsync(string @object) {
            this.unsetRedVoznjeAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetRedVoznjeAsync(string @object, object userState) {
            if ((this.unsetRedVoznjeOperationCompleted == null)) {
                this.unsetRedVoznjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetRedVoznjeOperationCompleted);
            }
            this.InvokeAsync("unsetRedVoznje", new object[] {
                        @object}, this.unsetRedVoznjeOperationCompleted, userState);
        }
        
        private void OnunsetRedVoznjeOperationCompleted(object arg) {
            if ((this.unsetRedVoznjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetRedVoznjeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setOtkazanaVoznja", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setOtkazanaVoznja([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("setOtkazanaVoznja", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setOtkazanaVoznjaAsync(string @object) {
            this.setOtkazanaVoznjaAsync(@object, null);
        }
        
        /// <remarks/>
        public void setOtkazanaVoznjaAsync(string @object, object userState) {
            if ((this.setOtkazanaVoznjaOperationCompleted == null)) {
                this.setOtkazanaVoznjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetOtkazanaVoznjaOperationCompleted);
            }
            this.InvokeAsync("setOtkazanaVoznja", new object[] {
                        @object}, this.setOtkazanaVoznjaOperationCompleted, userState);
        }
        
        private void OnsetOtkazanaVoznjaOperationCompleted(object arg) {
            if ((this.setOtkazanaVoznjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setOtkazanaVoznjaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getOtkazanaVoznja", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Otkazanavoznja getOtkazanaVoznja([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("getOtkazanaVoznja", new object[] {
                        id});
            return ((Application_Model_Otkazanavoznja)(results[0]));
        }
        
        /// <remarks/>
        public void getOtkazanaVoznjaAsync(System.Nullable<int> id) {
            this.getOtkazanaVoznjaAsync(id, null);
        }
        
        /// <remarks/>
        public void getOtkazanaVoznjaAsync(System.Nullable<int> id, object userState) {
            if ((this.getOtkazanaVoznjaOperationCompleted == null)) {
                this.getOtkazanaVoznjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOtkazanaVoznjaOperationCompleted);
            }
            this.InvokeAsync("getOtkazanaVoznja", new object[] {
                        id}, this.getOtkazanaVoznjaOperationCompleted, userState);
        }
        
        private void OngetOtkazanaVoznjaOperationCompleted(object arg) {
            if ((this.getOtkazanaVoznjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOtkazanaVoznjaCompleted(this, new getOtkazanaVoznjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetOtkazanaVoznja", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetOtkazanaVoznja([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetOtkazanaVoznja", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetOtkazanaVoznjaAsync(string @object) {
            this.unsetOtkazanaVoznjaAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetOtkazanaVoznjaAsync(string @object, object userState) {
            if ((this.unsetOtkazanaVoznjaOperationCompleted == null)) {
                this.unsetOtkazanaVoznjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetOtkazanaVoznjaOperationCompleted);
            }
            this.InvokeAsync("unsetOtkazanaVoznja", new object[] {
                        @object}, this.unsetOtkazanaVoznjaOperationCompleted, userState);
        }
        
        private void OnunsetOtkazanaVoznjaOperationCompleted(object arg) {
            if ((this.unsetOtkazanaVoznjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetOtkazanaVoznjaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#setTrasaStanica", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setTrasaStanica([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("setTrasaStanica", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void setTrasaStanicaAsync(string @object) {
            this.setTrasaStanicaAsync(@object, null);
        }
        
        /// <remarks/>
        public void setTrasaStanicaAsync(string @object, object userState) {
            if ((this.setTrasaStanicaOperationCompleted == null)) {
                this.setTrasaStanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTrasaStanicaOperationCompleted);
            }
            this.InvokeAsync("setTrasaStanica", new object[] {
                        @object}, this.setTrasaStanicaOperationCompleted, userState);
        }
        
        private void OnsetTrasaStanicaOperationCompleted(object arg) {
            if ((this.setTrasaStanicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTrasaStanicaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#getTrasaStanica", RequestNamespace="http://ps/Admin", ResponseNamespace="http://ps/Admin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Application_Model_Trasastanica getTrasaStanica([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] System.Nullable<int> id) {
            object[] results = this.Invoke("getTrasaStanica", new object[] {
                        id});
            return ((Application_Model_Trasastanica)(results[0]));
        }
        
        /// <remarks/>
        public void getTrasaStanicaAsync(System.Nullable<int> id) {
            this.getTrasaStanicaAsync(id, null);
        }
        
        /// <remarks/>
        public void getTrasaStanicaAsync(System.Nullable<int> id, object userState) {
            if ((this.getTrasaStanicaOperationCompleted == null)) {
                this.getTrasaStanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTrasaStanicaOperationCompleted);
            }
            this.InvokeAsync("getTrasaStanica", new object[] {
                        id}, this.getTrasaStanicaOperationCompleted, userState);
        }
        
        private void OngetTrasaStanicaOperationCompleted(object arg) {
            if ((this.getTrasaStanicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTrasaStanicaCompleted(this, new getTrasaStanicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ps/Admin#unsetTrasaStanica", RequestNamespace="http://ps/Admin", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void unsetTrasaStanica([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string @object) {
            this.Invoke("unsetTrasaStanica", new object[] {
                        @object});
        }
        
        /// <remarks/>
        public void unsetTrasaStanicaAsync(string @object) {
            this.unsetTrasaStanicaAsync(@object, null);
        }
        
        /// <remarks/>
        public void unsetTrasaStanicaAsync(string @object, object userState) {
            if ((this.unsetTrasaStanicaOperationCompleted == null)) {
                this.unsetTrasaStanicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsetTrasaStanicaOperationCompleted);
            }
            this.InvokeAsync("unsetTrasaStanica", new object[] {
                        @object}, this.unsetTrasaStanicaOperationCompleted, userState);
        }
        
        private void OnunsetTrasaStanicaOperationCompleted(object arg) {
            if ((this.unsetTrasaStanicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsetTrasaStanicaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }

        internal void setStanica(Stanice stanica)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Popust {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Trasastanica {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Otkazanavoznja {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Redvoznje {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Trasa {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Stanica {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ps/Admin")]
    public partial class Application_Model_Karta {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Ekarta_AdminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setPopustCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getPopustCompletedEventHandler(object sender, getPopustCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPopustCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPopustCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Popust Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Popust)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetPopustCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setKartaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getKartaCompletedEventHandler(object sender, getKartaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKartaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKartaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Karta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Karta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetKartaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void deactivateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setStanicaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getStanicaCompletedEventHandler(object sender, getStanicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStanicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStanicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Stanica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Stanica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetStanicaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setTrasaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTrasaCompletedEventHandler(object sender, getTrasaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTrasaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTrasaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Trasa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Trasa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetTrasaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setRedVoznjeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getRedVoznjeCompletedEventHandler(object sender, getRedVoznjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRedVoznjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRedVoznjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Redvoznje Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Redvoznje)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetRedVoznjeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setOtkazanaVoznjaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getOtkazanaVoznjaCompletedEventHandler(object sender, getOtkazanaVoznjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOtkazanaVoznjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOtkazanaVoznjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Otkazanavoznja Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Otkazanavoznja)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetOtkazanaVoznjaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setTrasaStanicaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTrasaStanicaCompletedEventHandler(object sender, getTrasaStanicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTrasaStanicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTrasaStanicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Application_Model_Trasastanica Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Application_Model_Trasastanica)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void unsetTrasaStanicaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591