//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektovanjeSoftvera.EkartaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ps", ConfigurationName="EkartaService.Ekarta_ServisPort")]
    public interface Ekarta_ServisPort {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://ps#Ekarta_Servis")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void Ekarta_Servis(ProjektovanjeSoftvera.EkartaService.Ekarta_Servis request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ps#stanicaUlazna", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ProjektovanjeSoftvera.EkartaService.stanicaUlaznaResponse stanicaUlazna(ProjektovanjeSoftvera.EkartaService.stanicaUlaznaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ekarta_Servis", WrapperNamespace="http://ps", IsWrapped=true)]
    public partial class Ekarta_Servis {
        
        public Ekarta_Servis() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stanicaUlazna", WrapperNamespace="http://ps", IsWrapped=true)]
    public partial class stanicaUlaznaRequest {
        
        public stanicaUlaznaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stanicaUlaznaResponse", WrapperNamespace="http://ps", IsWrapped=true)]
    public partial class stanicaUlaznaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public stanicaUlaznaResponse() {
        }
        
        public stanicaUlaznaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ekarta_ServisPortChannel : ProjektovanjeSoftvera.EkartaService.Ekarta_ServisPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ekarta_ServisPortClient : System.ServiceModel.ClientBase<ProjektovanjeSoftvera.EkartaService.Ekarta_ServisPort>, ProjektovanjeSoftvera.EkartaService.Ekarta_ServisPort {
        
        public Ekarta_ServisPortClient() {
        }
        
        public Ekarta_ServisPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ekarta_ServisPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ekarta_ServisPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ekarta_ServisPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ekarta_Servis(ProjektovanjeSoftvera.EkartaService.Ekarta_Servis request) {
            base.Channel.Ekarta_Servis(request);
        }
        
        public ProjektovanjeSoftvera.EkartaService.stanicaUlaznaResponse stanicaUlazna(ProjektovanjeSoftvera.EkartaService.stanicaUlaznaRequest request) {
            return base.Channel.stanicaUlazna(request);
        }
    }
}
